FROM docker.io/library/maven:3.8.7-eclipse-temurin-17 AS builder

WORKDIR /usr/local/app
COPY . .

RUN mvn clean test

FROM docker.io/rawdee/pmd

WORKDIR /usr/local/app
COPY . .

RUN pmd check -d /usr/local/app -R rulesets/java/quickstart.xml -r Static.txt